### ISSUE TITLE
Flavor of markdown being used?

### ISSUE THREAD

**Issue by m3hr** [mwhite/resume#29]
Some of the things that resume/pandoc render in the html seem to differ what I see in https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

especially with lists.

`* list item`
turns into
* list item

on, for example, GitHub flavored Markdown. But not with resume/pandoc?

**Comment by m3hr** [comment]
also having a weird issue where a link to an email with the email as the text renders in a monospaced font in the body of the resume, but appears as the normal serif font with a different email in the "contact information" section of the page

**Comment by m3hr** [comment]
....and another one where **bold**ing the lines of the contact information, either via `**` or `__` causes issues in the pdf. The former just puts the `**` in the text and the `__` breaks the alignment. I'll look into it if I can, thought I should report

**Comment by mwhite** [comment]
Yeah, the contact info parsing is kind of half-baked.  I think maybe it expects you to put a bare email address in the markdown, and then handles the linking for you.

As for the markdown flavor, it's Pandoc markdown.  I've clarified that in the readme.

I'd file your bolding issue as falling under #7.

Thanks!

**Comment by mwhite** [comment]
You use `<foo@example.com>` for email addresses (Markdown syntax for automatic email links).
