### ISSUE TITLE
strong emphasis does not work for pdf?

### ISSUE THREAD

**Issue by wjin** [mwhite/resume#31]
hi, with regard to Chinese, there is no 'strong emphasis' when converting to pdf file?

you could test it:

*中文*

or

**中文**

**Comment by mwhite** [comment]
I wonder if maybe the font this project is currently using for Chinese characters by default does not include bold-face versions of characters.

You can see the code for handling Chinese characters in header.tex.

```
\ifxetex
\usepackage{xeCJK}
\setCJKmainfont{WenQuanYi Zen Hei}
%\setmainfont[Mapping=tex-text]{TeX Gyre Pagella}
\fi
```

You can specify bold fonts as seen here:
http://tex.stackexchange.com/questions/215564/what-chinese-fonts-can-i-rely-on-to-be-in-mac-and-linux

I will try to look into this myself at another time.
