### ISSUE TITLE
! TeX capacity exceeded, sorry [save size=80000].

### ISSUE THREAD

**Issue by tasaif** [mwhite/resume#32]
```
export GRAVATAR_OPTION=--no-gravatar
export PANDOCARGS='--latex-engine=xelatex'
~/repos/resume (master) > make
rm -f *.html *.pdf
python resume.py tex < resume.md | pandoc --latex-engine=xelatex --template=./pandoc-templates/default.latex -H header.tex -o resume.pdf
pandoc: Error producing PDF from TeX source.
! TeX capacity exceeded, sorry [save size=80000].
\keyval_parse:n #1->\group_begin: 
                                  \tl_clear:N \l_keyval_sanitise_tl \tl_set:...
l.76 \begin{document}

make: *** [resume.pdf] Error 43

~/repos/resume (master) > cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

**Comment by mwhite** [comment]
This seems like a common error, but based on the location of the error, I think I've fixed this with a new version of the pandoc-templates submodule.

Out of curiosity, what version of xetex are you running?

**Comment by tasaif** [comment]
~/repos/personal_website (master) > xetex --version
XeTeX 3.1415926-2.4-0.9998 (TeX Live 2012/Debian)
kpathsea version 6.1.0
Copyright 2012 SIL International and Jonathan Kew.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 49.1 [with modifications for XeTeX]
Compiled with zlib version 1.2.7; using 1.2.7
Compiled with FreeType2 version 2.4.9; using 2.4.9
Compiled with fontconfig version 2.9.0; using 2.9.0
Compiled with libpng version 1.2.49; using 1.2.49
Compiled with poppler version 0.18.4

**Comment by mwhite** [comment]
I take it that updating to the latest version of the master branch and updating submodules didn't fix your issue?
