### ISSUE TITLE
Issues with rendering in latex when unicode characters is sneaking in.

### ISSUE THREAD

**Issue by mofosyne** [mwhite/resume#39]
Gets quite hard to locate the offending Unicode characters when using standard latex (Which cannot accept Unicode characters). (More of an issue in windows?)

I will push in a correction later on, but anyhow this is how I dealt with dropping such characters.

```
return "".join(lines)
```

is modified to:

```
    ans = "".join(lines)
    return ''.join(filter(lambda x: x in string.printable, ans))
```

**Comment by mwhite** [comment]
Already explained in README.
