### ISSUE TITLE
Missing tightlist command

### ISSUE THREAD

**Issue by qoelet** [mwhite/resume#40]
Required by Pandoc >= 1.14, fixed in https://github.com/jgm/pandoc-templates/pull/97

**Comment by mwhite** [comment]
I will fix this at some point but if someone wants to fork mwhite/pandoc-templates, update from latest jgm/pandoc-templates, and submit a PR, that would be awesome.  (It will probably involve resolving conflicts with some of the changes to mwhite/pandoc-templates such as handling Chinese characters.)

**Comment by qoelet** [comment]
@mwhite sure, I'll look into that.

**Comment by mwhite** [comment]
The fork of pandoc-templates may no longer be even required.
