### ISSUE TITLE
[pandoc-templates/default.latex] Error 1

### ISSUE THREAD

**Issue by MacLeeee** [mwhite/resume#49]
rm -f *.html *.pdf
git submodule update --init
Cloning into '/Users/liran/resume/pandoc-templates'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

fatal: clone of 'git@github.com:jgm/pandoc-templates.git' into submodule path '/Users/liran/resume/pandoc-templates' failed
make: *** [pandoc-templates/default.latex] Error 1

How to solve this?
Thx

@mwhite

**Comment by davidak** [comment]
@MacLeeee see my workaround in https://github.com/mwhite/resume/issues/50
