### ISSUE TITLE
error with  the git submodule?

### ISSUE THREAD

**Issue by frranck** [mwhite/resume#50]
Submodule 'pandoc-templates' (git@github.com:jgm/pandoc-templates.git) registered for path 'pandoc-templates'
Cloning into 'pandoc-templates'...
remote: Counting objects: 52, done.
remote: Total 52 (delta 0), reused 0 (delta 0), pack-reused 52
Receiving objects: 100% (52/52), 24.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (21/21), done.
Checking connectivity... done.
fatal: reference is not a tree: f9c70a54f8c21c3aeb3605a0967ae82c6d9c0753
Unable to checkout 'f9c70a54f8c21c3aeb3605a0967ae82c6d9c0753' in submodule path 'pandoc-templates'
Makefile:30: recipe for target 'pandoc-templates/default.latex' failed
make: *** [pandoc-templates/default.latex] Error 1

**Comment by davidak** [comment]
```
[nix-shell:~/code/resume]$ make
rm -f *.html *.pdf
git submodule update --init
error: Server does not allow request for unadvertised object f9c70a54f8c21c3aeb3605a0967ae82c6d9c0753
Fetched in submodule path 'pandoc-templates', but it did not contain f9c70a54f8c21c3aeb3605a0967ae82c6d9c0753. Direct fetching of that commit failed.
make: *** [Makefile:30: pandoc-templates/default.latex] Error 1

```

**Comment by davidak** [comment]
Workaround:

Comment out the last 2 lines in `Makefile`:
```
#$(LATEX_TEMPLATE):
#       git submodule update --init
```

Then clone the lastest version of the repo:
```
[nix-shell:~/code/resume]$ rm -rf pandoc-templates/
[nix-shell:~/code/resume]$ git clone https://github.com/jgm/pandoc-templates.git
Cloning into 'pandoc-templates'...
remote: Counting objects: 52, done.
remote: Total 52 (delta 0), reused 0 (delta 0), pack-reused 52
Unpacking objects: 100% (52/52), done.

```
