### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by HedgehogCode** [mwhite/resume#51]
Without a license, nobody can legally use, copy, distribute, or modify the code as stated here: [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/)

Is this intended? If so, I would recommend adding a section to the README which says that.

Otherwise, I would be pleased to see this project under an open source license. ([https://choosealicense.com](https://choosealicense.com))

**Comment by mwhite** [comment]
Thanks for noticing, I've added the MIT License.

**Comment by HedgehogCode** [comment]
Awesome! Thank you.
