### ISSUE TITLE
! Argument of \paragraph has an extra }.

### ISSUE THREAD

**Issue by davidak** [mwhite/resume#52]
The PDF generation fails:

```
[nix-shell:~/code/resume]$ make
rm -f *.html *.pdf
python resume.py tex < resume.md | pandoc  --template=./pandoc-templates/default.latex -H header.tex -o resume.pdf
! Argument of \paragraph has an extra }.
<inserted text> 
                \par 
l.1290 \ttl@extract\paragraph

pandoc: Error producing PDF
make: *** [Makefile:16: resume.pdf] Error 43
```

Maybe it's because i use the latest `pandoc-templates`. There is a problem with your submodule. https://github.com/mwhite/resume/issues/50

---

I run it in a [nix-shell](https://nixos.org/nix/) with these packages:
```
nix-shell -p texlive.combined.scheme-full gyre-fonts lmodern pandoc python
```

**Comment by mwhite** [comment]
Thanks for the report, fixed using the solution at https://stackoverflow.com/questions/42916124/not-able-to-use-titlesec-with-markdown-and-pandoc.
